png("plot3.png", width=480, height=480)
with(df_tidy, plot(DateTime, Sub_metering_1, type = "n", ylab="Energy Sub Metering", xlab=""))
with(df_tidy, lines(DateTime, Sub_metering_1, col = "black"))
with(df_tidy, lines(DateTime, Sub_metering_2, col = "red"))
with(df_tidy, lines(DateTime, Sub_metering_3, col = "blue"))
legend("topright",lty=c(1,1,1), col=c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
#dev.copy(png, file="plot3.png")
dev.off()
