par(mfrow =c(2,2))
with(df_tidy, {
    plot(DateTime,Global_active_power, ylab = "Global Active Power (kilowatts)",type="l",xlab="")
    plot(DateTime,Voltage, ylab = "Global Active Power (kilowatts)",type="l")
    with(df_tidy, plot(DateTime, Sub_metering_1, type = "n", ylab="Energy Sub Metering", xlab=""))
    with(df_tidy, lines(DateTime, Sub_metering_1, col = "black"))
    with(df_tidy, lines(DateTime, Sub_metering_2, col = "red"))
    with(df_tidy, lines(DateTime, Sub_metering_3, col = "blue"))
    legend("topright",lty=c(1,1,1), col=c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
    plot(DateTime,Global_reactive_power, ylab = "Global Active Power (kilowatts)",type="l",)
})
dev.copy(png, file="plot4.png")
dev.off()
